### ISSUE TITLE
GUI for Paworld-Save-Pal

### ISSUE THREAD

**Issue by cwodrs** [oMaN-Rod/palworld-save-pal#3]
I have downloaded and use this product and I love It, I just have some questions:

1.  Is there a Limit on what and how much  you can put into your Inventory?
2. The GUI is a Dark Background which I love but most of the buttons are invisible unless you happen to mouse over them.
3. I was able to add 2 Pals and was able to clone those 2, but the whole Pal screen would shift up to where you can only see the bottom part of the pal info when I click on it to edit it, I finally figured out by hitting Tab brought the screen back into view!

The reason I asked the question in 1. is that my first swing of it, I added a Rocket Launcher and Rockets, no issues everything was there when I started back up, put I added a whole bunch of other stuff in the Inventory, And when I replaced the file and started the server, it would start then crash, I am guessing it didn't like what I was adding. Would it be quicker if I join the discord listed on the Nexsus Post?

Thank You
Randy Spencer

**Comment by oMaN-Rod** [comment]
I know we reviewed on discord but I will answer the questions here too in case someone else stumbles across this seeking the same answers.

1. There are 42 Inventory slots, 100 Key Items slots, 4 Weapon Slots, 5 Food Slots, and 8 Equipment slots that can be filled. As far as item types and quantities are concerned, anything listed in the [Presets](https://github.com/oMaN-Rod/palworld-save-pal/wiki/Presets) page has been tested, for everything else proceed with caution and let me know if you run into any issues here or on discord.
2. I can work on making the buttons more obvious, I also might just go ahead and make a few themes to select from with light and dark modes. Stay tuned.
3. This was fixed in v0.4 available in [Releases](https://github.com/oMaN-Rod/palworld-save-pal/releases)
